### PR TITLE
New colored icon and improved logo

### PR DESCRIPTION
**Pull request by martymarty004**
# Proposed Changes
I'm proposing a new colored version of the icon and logo to improve the design and to add support for Home Assistant "Running" and "Stopped" (greyed out) add-on state.

## Related Issues
GH-24 

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by martymarty004** [comment]
I still have the project files, so if there is anything to change I can do that quickly.

**Comment by sinclairpaul** [comment]
Thanks, looks good, though the black text in the logo doesn't go well with dark mode, not sure what's the best approach for that.

**Comment by martymarty004** [comment]
> Thanks, looks good, though the black text in the logo doesn't go well with dark mode, not sure what's the best approach for that.

Maybe I can try with light grey

**Comment by martymarty004** [comment]
Opening it with Windows Photos in light and dark mode doesn't look that bad

image

image

**Comment by sinclairpaul** [comment]
Thanks looks good to me

**Pull request merged**
